Ok, I think I see what is going on; the strings in the array (i.e. the array of chars in the array) were not themselves initialized, so it caused a segfault. One solution is to dynamically allocate these strings up as needed, but, it seems we would just need to specify the length of those chars at declaration to initialize it that way; doing it this way, however, breaks:
buffer.c:8:22: error: cannot convert ‘char (*)[50]’ to ‘char**’ in initialization
 char** buffer_curr = buffer_str;
                      ^
I am beginning to suspect that maybe statically-created arrays have some sort of binding to typing, which is why just pointers won't work here.... ahhh man, this is confusing, will need to study this more carefully